Repository spotipy-dev/spotipy, pull requests merged in 2020-01, with the labels that each got.

#420 Trim '?<key>' when extracting ID from HTTP URLs
  CHANGELOG.md
  spotipy/client.py
Labels: bug

#269 Refactor client internal calls to allow keepalive
  CHANGELOG.md
  spotipy/client.py
  tests/tests.py
Labels: enhancement

#422 List of tracks in a playlist added
  CHANGELOG.md
  docs/index.rst
  examples/read_a_playlist.py
  examples/user_playlists_contents.py
  examples/user_starred_playlist.py
  spotipy/client.py
  tests/test_auth.py
Labels: duplicate, missing-endpoint

#416 Support to upload playlist thumbnails
  CHANGELOG.md
  spotipy/client.py
  tests/test_auth.py
Labels: missing-endpoint

#428 Automatic refresh of Authorization Code Flow Tokens in long-running Applications
  CHANGELOG.md
  examples/long_running.py
  spotipy/client.py
  spotipy/oauth2.py
  spotipy/util.py
Labels: enhancement
