Repository spotipy-dev/spotipy, pull requests merged in 2025-01, with the labels that each got.

#1171 Update docs for `current_user_top_artists`
  CHANGELOG.md
  spotipy/client.py
Labels: documentation

#1178 Formatted strings
  CHANGELOG.md
  docs/index.rst
  examples/artist_albums.py
  examples/artist_discography.py
  examples/artist_recommendations.py
  examples/follow_playlist.py
  examples/my_playlists.py
  examples/show_my_saved_tracks.py
  examples/track_recommendations.py
  examples/user_playlists_contents.py
  examples/user_public_playlists.py
  spotipy/cache_handler.py
  spotipy/client.py
  spotipy/exceptions.py
  spotipy/oauth2.py
  tests/integration/user_endpoints/test.py
Labels: enhancement

#961 Codebase Refactor for v3
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  TUTORIAL.md
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  examples/app.py
  examples/artist_albums.py
  examples/artist_discography.py
  examples/artist_recommendations.py
  examples/playlist_add_items.py
  examples/playlist_all_non_local_tracks.py
  examples/remove_specific_tracks_from_playlist.py
  examples/search.py
  examples/show_featured_playlists.py
  examples/show_new_releases.py
  examples/show_related.py
  examples/show_user.py
  examples/simple_search_artist_image_url.py
  examples/track_recommendations.py
  examples/user_public_playlists.py
  spotipy/cache_handler.py
  spotipy/client.py
  spotipy/oauth2.py
  spotipy/util.py
  tests/integration/non_user_endpoints/test.py
  tests/unit/test_scopes.py
Labels: enhancement, spotipy3

#1153 Add type annotations to cache_handler.py
  CHANGELOG.md
  spotipy/cache_handler.py
Labels: spotipy3

#914 updated functionality of playlist_add_items()
  CHANGELOG.md
  spotipy/client.py
  tests/integration/user_endpoints/test.py
Labels: bug, spotipy3
